spring:
  application:
    name: point-service

  config:
    import: 'optional:configserver: '
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    prefer-ip-address: false
    hostname: ecs-load-balancer-597540403.ap-northeast-2.elb.amazonaws.com
    non-secure-port: 4000
    health-check-url-path: /actuator/health

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.79.151.83:3150/eureka/

server:
  port: 4000